### PR TITLE
Don't inline native source builders

### LINKED ISSUE #581: Update to kotlin 1.4.30
Kotlin 1.4.30 has been released

I am not sure if the below build error is cause by reaktive when trying to build an iOS framework using kotlin 1.4.30, the error is a bit vague, but the only place I use onError is during some reaktive streams.

e: Compilation failed: FUN name:onError_6 visibility:public modality:OPEN <> ($this:co.app.shared.extensions.<no name provided>_1<kotlin.Unit>, error:kotlin.Throwable) returnType:kotlin.Unit

### PR DESCRIPTION
**Pull request by arkivanov**
Due to [KT-44764](https://youtrack.jetbrains.com/issue/KT-44764).
Fixes #581.

### CODE REVIEW

**Review by CherryPerry — APPROVED** [review]

**Comment by CherryPerry** [comment]
Create issue to check and revert it later?

**Comment by arkivanov** [comment]
Filed #587
