### ISSUE TITLE
Coroutines 1.7.1 causing internal compiler error

### ISSUE THREAD

**Issue by minaEweida** [badoo/Reaktive#755]
When upgrading to 2.0.0-alpha01 I am running into 

```
e: Compilation failed: Internal compiler error: no implementation found for FUN DEFAULT_PROPERTY_ACCESSOR name:<get-parent> visibility:public modality:ABSTRACT <> ($this:kotlinx.coroutines.Job) returnType:kotlinx.coroutines.Job?
```
This is tracked [here](https://youtrack.jetbrains.com/issue/KTOR-5728)

Will it make sense to downgrade to 1.7.0 till this issue is resolved with Ktor?

**Comment by arkivanov** [comment]
Thanks for reporting! Will downgrading coroutines to `1.7.0` actually fix the issue? There is a comment in that issue saying:

> Still happens on coroutines `1.7.0` and ktor `2.3.0` and kotlin `1.8.21`

Meantime, perhaps you could [downgrade](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html#sec:enforcing_dependency_version) coroutines in your project if needed? Would this work for you?

**Comment by minaEweida** [comment]
Yes makes sense, thanks for your reply
