### ISSUE TITLE
Update to kotlin 1.4.30

### ISSUE THREAD

**Issue by mikezliu** [badoo/Reaktive#581]
Kotlin 1.4.30 has been released

I am not sure if the below build error is cause by reaktive when trying to build an iOS framework using kotlin 1.4.30, the error is a bit vague, but the only place I use onError is during some reaktive streams.

e: Compilation failed: FUN name:onError_6 visibility:public modality:OPEN <> ($this:co.app.shared.extensions.<no name provided>_1<kotlin.Unit>, error:kotlin.Throwable) returnType:kotlin.Unit

**Comment by arkivanov** [comment]
Thanks for the issue. Kotlin 1.4.30 has same ABI as previous version, so should be fine. Is it possible for you to provide a reproducer?

**Comment by mikezliu** [comment]
I'll try to narrow it down

**Comment by arkivanov** [comment]
Thanks, that's would be really helpful

**Comment by mikezliu** [comment]
Posted a bug here: https://youtrack.jetbrains.com/issue/KT-44764

**Comment by arkivanov** [comment]
Thanks @mikezliu ! This looks indeed looks like a compiler bug. We will release an update with Kotlin 1.4.30 a bit later, maybe this will help.

**Comment by mikezliu** [comment]
Fyi, the build issue seems to be caused by this:

import com.badoo.reaktive.observable.*

fun testFunction(): Observable<Unit> =
        observable { emitter ->

        }

If I change it to the following, the error goes away:

import com.badoo.reaktive.observable.*

fun testFunction(): Observable<Unit> =
        observableOfNever()

So it seems to be coming from the observable expected function

I'll try with the new reaktive library version later

**Comment by arkivanov** [comment]
I just hit the same compile error. Updated the KT-44764 with a reproducer. Will try publishing a new version of Reaktive locally and check if it helps.

**Comment by arkivanov** [comment]
Unfortunately, update to Kotlin 1.4.30 does not help. We should wait for the response in KT-44764.

**Comment by arkivanov** [comment]
A have found a way to workaround the error, will PR tomorrow.

**Comment by arkivanov** [comment]
@mikezliu The issue should now be fixed.

**Comment by pfaffenrodt** [comment]
@arkivanov What about  `1.1.20-nmtc` ?

**Comment by arkivanov** [comment]
@pfaffenrodt ahh, forgot about it. Will publish now

**Comment by arkivanov** [comment]
@pfaffenrodt Published!
